version: '3.8'

services:
  mysql:
    container_name: mysql-sql-wallet
    image: mysql
    environment:
      MYSQL_DATABASE: mysql-sql-wallet
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spring-wallet
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-wallet
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mysql:
    driver: local

networks:
  spring-wallet:
    driver: bridge
